[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tag"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "Instagram"
  pre = "fab instagram"
  url = "https://www.instagram.com/a_wei_drawer/"
  weight = 10

# [[social]]
  # name = "Youtube"
  # pre = "fab youtube"
  # url = "https://www.youtube.com/channel/UCyz4bBUizrgw76yhiOE9eJA"
  # weight = 20

# [[social]]
  # name = "Medium"
  # pre = "fab medium"
  # url = "https://medium.com/"
  # weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation